config/routes.rb
Rails.application.routes.draw do
  root :to => 'issues#list_page'
  
  resources :issues do
    member do
     get :show  
    end
    
    collection do
      get :index
      get '/issues/list_page' => 'issues#list_page', :as => :list_page
    end
  end
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :issues do
        member do
          get :show
        end
        collection do
          get :index
          post :create
        end
      end
    end
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
    
end

app/controllers/api/v1/issues_controller.rb
class Api::V1::IssuesController < Api::V1::BaseController
  skip_before_action :verify_authenticity_token
  
  def index
    issues = Issue.all.order(:created_at)
    render json: issues.to_json(:only => [
      :id, 
      :action,
      :repository_id,
      :repository_name,
      :owner_name,
      :created_at,
      :updated_at
    ])
  end
  
  def new
    
  end
  
  def create
    parsed_request = JSON.parse(request.body.read)
    
    issue = Issue.new(
      action: parsed_request["action"],
      repository_id: parsed_request["issue"]["id"],
      repository_name: parsed_request["repository"]["name"],
      owner_name: parsed_request["repository"]["owner"]["login"]
    )
    
    render json: { data: "#{issue.to_json}" }, status: issue.save ? 201 : 400
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  
  def index
    @issues = Issue.order(:created_at)
  end
  
  def show
    @issue = Issue.find(params[:id])
  end

  def list_page
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/index.html.erb
<div class="container">
  <div class="section">
 
    <div class="row">
      <div class="col s12 m12">
        <div class="icon-block">
          <table>
            <thead>
              <% if @issues.any? %>
                <tr>
                  <th></th>
                  <th>id</th>
                  <th>action</th>
                  <th>repository id</th>
                  <th>repository name</th>
                  <th>owner name</th>
                  <th>created at</th>
                  <th>updated at</th>
                </tr>
              <% else %>
                <div class="col s12 m12">
                  <div class="icon-block">
                    <h2 class="center light-blue-text"><i class="material-icons">error</i></h2>
                    <h5 class="center">Ainda não existem repositórios cadastrados</h5>
                    <p class="light"></p>
                  </div>
                </div>
              <% end %>
            </thead>
    
            <tbody>
              <% @issues.each do |issue| %>
                <tr>
                  <td><%= link_to "Visualizar", issue_path(issue), class:"btn-small waves-effect waves-light light-blue" %></td>
                  <td><%= issue.id%></td>
                  <td><%= issue.action %></td>
                  <td><%= issue.repository_id%></td>
                  <td><%= issue.repository_name%></td>
                  <td><%= issue.owner_name%></td>
                  <td><%= issue.created_at%></td>
                  <td><%= issue.updated_at%></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    
  </div>
</div>
 

app/views/issues/list_page.html.erb
<div class="container">
  <div class="section">
    
    <div class="container">
      <br><br>
      <h2 class="header center orange-text">Zaitt</h2>
      <div class="row center">
        <h5 class="header col s12 light">Busque e liste todas as issues de um repositório aqui</h5>
      </div>
      <br><br>
    </div>
    <div class="row center">
      <%= link_to "Inicie Agora", issues_path, class:"btn-large waves-effect waves-light orange" %>
    </div>
    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Rápido e prático</h5>
 
          <p class="light"></p>
        </div>
      </div>
 
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
          <h5 class="center">Focado em User Experience</h5>
 
          <p class="light"></p>
        </div>
      </div>
 
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Fácil de utilizar</h5>
 
          <p class="light"></p>
        </div>
      </div>
    </div>
 
  </div>
</div>
 

app/views/issues/show.html.erb
<div class="container">
  <div class="section">

    <div class="row">
      <div class="col s12 m12">
        <div class="icon-block">
      
          <div class="row left">
            <%= link_to "Voltar", issues_path, class:"btn-small waves-effect waves-light orange" %>
          </div>
      
          <table>
            <thead>
              <tr>
                <th>id</th>
                <th>action</th>
                <th>repository id</th>
                <th>repository name</th>
                <th>owner name</th>
                <th>created at</th>
                <th>updated at</th>
              </tr>
            </thead>
            
            <tbody>
              <tr>
                <td><%= @issue.id %></td>
                <td><%= @issue.action %></td>
                <td><%= @issue.repository_id %></td>
                <td><%= @issue.repository_name %></td>
                <td><%= @issue.owner_name %></td>
                <td><%= @issue.created_at %></td>
                <td><%= @issue.updated_at %></td>
              </tr>
            </tbody>
          </table>
          
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="light-blue lighten-1" role="navigation">
  <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo"></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="#"></a></li>
    </ul>
 
    <a href="/" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">home</i></a>
  </div>
</nav>

<div class="section no-pad-bot" id="index-banner">

</div>  

<%= yield %>

</body>
</html>